---
- name: "Copy Backend file"
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend-app

- name: "Unarchive backend file"
  ansible.builtin.shell: tar -xzf artifact.tar.gz
  args:
    chdir: /home/ubuntu

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend-app
    npm i
- name: "excuting with pm"
  shell: |
      cd /home/ubuntu/backend-app/dist
      pm2 stop default
      pm2 start main.js
- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu




